const columnList = [
	{
		"jnpfKey":"billRule",
		"fullName":"采购单号",
		"fullNameI18nCode":[
			""
		],
		"label":"采购单号",
		"sortable":false,
		"align":"left",
		"__config__":{
			"formId":101,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"billRule",
			"defaultValue":null,
			"noShow":false,
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"rule":"cgdj",
			"className":[],
			"label":"采购单号",
			"trigger":"change",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518489368,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-documents",
			"ruleName":"采购单据",
			"tag":"JnpfInput",
			"tableAlign":"left",
			"span":12
		},
		"readonly":true,
		"prop":"F_Purchase_number",
		"width":null,
		"__vModel__":"F_Purchase_number",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"id":"F_Purchase_number",
		"placeholder":"系统自动生成",
		"labelI18nCode":""
	},
	{
		"clearable":true,
		"jnpfKey":"usersSelect",
		"ableIds":[],
		"multiple":false,
		"fullName":"采购申请人",
		"fullNameI18nCode":[
			""
		],
		"label":"采购申请人",
		"sortable":false,
		"align":"left",
		"__config__":{
			"formId":102,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"usersSelect",
			"defaultValue":"",
			"noShow":false,
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"采购申请人",
			"trigger":"change",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518535374,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-founder",
			"defaultCurrent":false,
			"tag":"JnpfUsersSelect",
			"regList":[],
			"tableAlign":"left",
			"span":12
		},
		"prop":"F_Applys",
		"width":null,
		"__vModel__":"F_Applys",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"selectType":"all",
		"disabled":false,
		"id":"F_Applys",
		"placeholder":"请选择",
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	},
	{
		"filterable":false,
		"clearable":true,
		"jnpfKey":"depSelect",
		"ableIds":[],
		"multiple":false,
		"fullName":"所属部门",
		"fullNameI18nCode":[
			""
		],
		"label":"所属部门",
		"sortable":false,
		"align":"left",
		"__config__":{
			"formId":103,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"depSelect",
			"defaultValue":"",
			"noShow":false,
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"所属部门",
			"trigger":"change",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518595157,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-tree-department1",
			"defaultCurrent":true,
			"tag":"JnpfDepSelect",
			"regList":[],
			"tableAlign":"left",
			"span":12
		},
		"prop":"F_Dep_Name",
		"width":null,
		"__vModel__":"F_Dep_Name",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"selectType":"all",
		"disabled":false,
		"id":"F_Dep_Name",
		"placeholder":"请选择",
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	},
	{
		"clearable":true,
		"jnpfKey":"datePicker",
		"format":"yyyy-MM-dd",
		"fullName":"采购申请日期",
		"fullNameI18nCode":[
			""
		],
		"label":"采购申请日期",
		"sortable":false,
		"align":"left",
		"__config__":{
			"endRelationField":"",
			"defaultValue":null,
			"dragDisabled":false,
			"className":[],
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518622997,
			"tagIcon":"icon-ym icon-ym-generator-date",
			"startRelationField":"",
			"defaultCurrent":false,
			"tag":"JnpfDatePicker",
			"formId":104,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"datePicker",
			"noShow":false,
			"endTimeTarget":1,
			"tipLabel":"",
			"tableFixed":"none",
			"startTimeType":1,
			"endTimeRule":false,
			"label":"采购申请日期",
			"trigger":"change",
			"startTimeRule":false,
			"startTimeValue":null,
			"endTimeValue":null,
			"endTimeType":1,
			"layout":"colFormItem",
			"startTimeTarget":1,
			"regList":[],
			"tableAlign":"left",
			"span":12
		},
		"prop":"F_Purchase",
		"width":null,
		"__vModel__":"F_Purchase",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"startTime":null,
		"disabled":false,
		"id":"F_Purchase",
		"placeholder":"请选择",
		"endTime":null,
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	},
	{
		"clearable":true,
		"maxlength":null,
		"jnpfKey":"textarea",
		"fullName":"采购原因",
		"fullNameI18nCode":[
			""
		],
		"label":"采购原因",
		"sortable":false,
		"align":"left",
		"autoSize":{
			"minRows":4,
			"maxRows":4
		},
		"showCount":false,
		"__config__":{
			"formId":105,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"textarea",
			"noShow":false,
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"采购原因",
			"trigger":"blur",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518636353,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-textarea",
			"tag":"JnpfTextarea",
			"regList":[],
			"tableAlign":"left",
			"span":24
		},
		"readonly":false,
		"prop":"F_Reasons",
		"width":null,
		"__vModel__":"F_Reasons",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"disabled":false,
		"id":"F_Reasons",
		"placeholder":"请输入",
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	},
	{
		"clearable":true,
		"maxlength":null,
		"jnpfKey":"textarea",
		"fullName":"备注",
		"fullNameI18nCode":[
			""
		],
		"label":"备注",
		"sortable":false,
		"align":"left",
		"autoSize":{
			"minRows":4,
			"maxRows":4
		},
		"showCount":false,
		"__config__":{
			"formId":106,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"textarea",
			"noShow":false,
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"备注",
			"trigger":"blur",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518645187,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-textarea",
			"tag":"JnpfTextarea",
			"regList":[],
			"tableAlign":"left",
			"span":24
		},
		"readonly":false,
		"prop":"F_Remarks",
		"width":null,
		"__vModel__":"F_Remarks",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"disabled":false,
		"id":"F_Remarks",
		"placeholder":"请输入",
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	},
	{
		"useScan":false,
		"suffixIcon":"",
		"fullNameI18nCode":[
			"",
			""
		],
		"align":"left",
		"showCount":false,
		"__config__":{
			"relationTable":"test_purchaseorder",
			"formId":112,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"input",
			"noShow":false,
			"parentVModel":"tableField111",
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"产品名称",
			"trigger":"blur",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518735879,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-input",
			"isSubTable":true,
			"tag":"JnpfInput",
			"regList":[],
			"tableAlign":"left",
			"span":24
		},
		"readonly":false,
		"prop":"tableField111-F_Product_name",
		"__vModel__":"F_Product_name",
		"disabled":false,
		"id":"tableField111-F_Product_name",
		"placeholder":"请输入",
		"addonBefore":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		},
		"clearable":true,
		"maxlength":null,
		"jnpfKey":"input",
		"fullName":"采购明细-产品名称",
		"label":"采购明细-产品名称",
		"sortable":false,
		"addonAfter":"",
		"maskConfig":{
			"prefixType":1,
			"useUnrealMask":false,
			"maskType":1,
			"unrealMaskLength":1,
			"prefixLimit":0,
			"suffixLimit":0,
			"filler":"*",
			"prefixSpecifyChar":"",
			"suffixType":1,
			"ignoreChar":"",
			"suffixSpecifyChar":""
		},
		"width":null,
		"useMask":false,
		"showPassword":false,
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"prefixIcon":"",
		"labelI18nCode":""
	},
	{
		"useScan":false,
		"suffixIcon":"",
		"fullNameI18nCode":[
			"",
			""
		],
		"align":"left",
		"showCount":false,
		"__config__":{
			"relationTable":"test_purchaseorder",
			"formId":113,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"input",
			"noShow":false,
			"parentVModel":"tableField111",
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"产品编码",
			"trigger":"blur",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518753235,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-input",
			"isSubTable":true,
			"tag":"JnpfInput",
			"regList":[],
			"tableAlign":"left",
			"span":24
		},
		"readonly":false,
		"prop":"tableField111-F_Product_Code",
		"__vModel__":"F_Product_Code",
		"disabled":false,
		"id":"tableField111-F_Product_Code",
		"placeholder":"请输入",
		"addonBefore":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		},
		"clearable":true,
		"maxlength":null,
		"jnpfKey":"input",
		"fullName":"采购明细-产品编码",
		"label":"采购明细-产品编码",
		"sortable":false,
		"addonAfter":"",
		"maskConfig":{
			"prefixType":1,
			"useUnrealMask":false,
			"maskType":1,
			"unrealMaskLength":1,
			"prefixLimit":0,
			"suffixLimit":0,
			"filler":"*",
			"prefixSpecifyChar":"",
			"suffixType":1,
			"ignoreChar":"",
			"suffixSpecifyChar":""
		},
		"width":null,
		"useMask":false,
		"showPassword":false,
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"prefixIcon":"",
		"labelI18nCode":""
	},
	{
		"useScan":false,
		"suffixIcon":"",
		"fullNameI18nCode":[
			"",
			""
		],
		"align":"left",
		"showCount":false,
		"__config__":{
			"relationTable":"test_purchaseorder",
			"formId":114,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"input",
			"noShow":false,
			"parentVModel":"tableField111",
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"产品分类",
			"trigger":"blur",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518757223,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-input",
			"isSubTable":true,
			"tag":"JnpfInput",
			"regList":[],
			"tableAlign":"left",
			"span":24
		},
		"readonly":false,
		"prop":"tableField111-F_Product_category",
		"__vModel__":"F_Product_category",
		"disabled":false,
		"id":"tableField111-F_Product_category",
		"placeholder":"请输入",
		"addonBefore":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		},
		"clearable":true,
		"maxlength":null,
		"jnpfKey":"input",
		"fullName":"采购明细-产品分类",
		"label":"采购明细-产品分类",
		"sortable":false,
		"addonAfter":"",
		"maskConfig":{
			"prefixType":1,
			"useUnrealMask":false,
			"maskType":1,
			"unrealMaskLength":1,
			"prefixLimit":0,
			"suffixLimit":0,
			"filler":"*",
			"prefixSpecifyChar":"",
			"suffixType":1,
			"ignoreChar":"",
			"suffixSpecifyChar":""
		},
		"width":null,
		"useMask":false,
		"showPassword":false,
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"prefixIcon":"",
		"labelI18nCode":""
	},
	{
		"useScan":false,
		"suffixIcon":"",
		"fullNameI18nCode":[
			"",
			""
		],
		"align":"left",
		"showCount":false,
		"__config__":{
			"relationTable":"test_purchaseorder",
			"formId":115,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"input",
			"noShow":false,
			"parentVModel":"tableField111",
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"规格",
			"trigger":"blur",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518760024,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-input",
			"isSubTable":true,
			"tag":"JnpfInput",
			"regList":[],
			"tableAlign":"left",
			"span":24
		},
		"readonly":false,
		"prop":"tableField111-F_Specifications",
		"__vModel__":"F_Specifications",
		"disabled":false,
		"id":"tableField111-F_Specifications",
		"placeholder":"请输入",
		"addonBefore":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		},
		"clearable":true,
		"maxlength":null,
		"jnpfKey":"input",
		"fullName":"采购明细-规格",
		"label":"采购明细-规格",
		"sortable":false,
		"addonAfter":"",
		"maskConfig":{
			"prefixType":1,
			"useUnrealMask":false,
			"maskType":1,
			"unrealMaskLength":1,
			"prefixLimit":0,
			"suffixLimit":0,
			"filler":"*",
			"prefixSpecifyChar":"",
			"suffixType":1,
			"ignoreChar":"",
			"suffixSpecifyChar":""
		},
		"width":null,
		"useMask":false,
		"showPassword":false,
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"prefixIcon":"",
		"labelI18nCode":""
	},
	{
		"useScan":false,
		"suffixIcon":"",
		"fullNameI18nCode":[
			"",
			""
		],
		"align":"left",
		"showCount":false,
		"__config__":{
			"relationTable":"test_purchaseorder",
			"formId":116,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"input",
			"noShow":false,
			"parentVModel":"tableField111",
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"产品单位",
			"trigger":"blur",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518763542,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-input",
			"isSubTable":true,
			"tag":"JnpfInput",
			"regList":[],
			"tableAlign":"left",
			"span":24
		},
		"readonly":false,
		"prop":"tableField111-F_Unit",
		"__vModel__":"F_Unit",
		"disabled":false,
		"id":"tableField111-F_Unit",
		"placeholder":"请输入",
		"addonBefore":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		},
		"clearable":true,
		"maxlength":null,
		"jnpfKey":"input",
		"fullName":"采购明细-产品单位",
		"label":"采购明细-产品单位",
		"sortable":false,
		"addonAfter":"",
		"maskConfig":{
			"prefixType":1,
			"useUnrealMask":false,
			"maskType":1,
			"unrealMaskLength":1,
			"prefixLimit":0,
			"suffixLimit":0,
			"filler":"*",
			"prefixSpecifyChar":"",
			"suffixType":1,
			"ignoreChar":"",
			"suffixSpecifyChar":""
		},
		"width":null,
		"useMask":false,
		"showPassword":false,
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"prefixIcon":"",
		"labelI18nCode":""
	},
	{
		"controls":false,
		"jnpfKey":"inputNumber",
		"fullName":"采购明细-数量",
		"fullNameI18nCode":[
			"",
			""
		],
		"label":"采购明细-数量",
		"sortable":false,
		"align":"left",
		"thousands":false,
		"isAmountChinese":false,
		"addonAfter":"",
		"__config__":{
			"formId":117,
			"relationTable":"test_purchaseorder",
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"inputNumber",
			"noShow":false,
			"parentVModel":"tableField111",
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"数量",
			"trigger":[
				"blur",
				"change"
			],
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518785979,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-number",
			"isSubTable":true,
			"tag":"JnpfInputNumber",
			"regList":[],
			"tableAlign":"left",
			"span":24
		},
		"prop":"tableField111-F_Numbers",
		"width":null,
		"__vModel__":"F_Numbers",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"step":1,
		"disabled":false,
		"id":"tableField111-F_Numbers",
		"placeholder":"请输入",
		"addonBefore":"",
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	},
	{
		"jnpfKey":"createUser",
		"fullName":"创建用户",
		"fullNameI18nCode":[
			""
		],
		"label":"创建用户",
		"sortable":false,
		"align":"left",
		"type":"currUser",
		"__config__":{
			"formId":107,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"createUser",
			"defaultValue":"",
			"noShow":true,
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"创建用户",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518651930,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-founder",
			"tag":"JnpfOpenData",
			"tableAlign":"left",
			"span":24
		},
		"readonly":true,
		"prop":"F_CreatorUserId",
		"width":null,
		"__vModel__":"F_CreatorUserId",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"id":"F_CreatorUserId",
		"placeholder":"",
		"labelI18nCode":""
	},
	{
		"jnpfKey":"createTime",
		"fullName":"创建时间",
		"fullNameI18nCode":[
			""
		],
		"label":"创建时间",
		"sortable":false,
		"align":"left",
		"type":"currTime",
		"__config__":{
			"formId":108,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"createTime",
			"defaultValue":"",
			"noShow":true,
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"创建时间",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518656844,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-createtime",
			"tag":"JnpfOpenData",
			"tableAlign":"left",
			"span":24
		},
		"readonly":true,
		"prop":"F_CreatorTime",
		"width":null,
		"__vModel__":"F_CreatorTime",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"id":"F_CreatorTime",
		"placeholder":"",
		"labelI18nCode":""
	},
	{
		"jnpfKey":"modifyUser",
		"fullName":"修改用户",
		"fullNameI18nCode":[
			""
		],
		"label":"修改用户",
		"sortable":false,
		"align":"left",
		"__config__":{
			"formId":109,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"modifyUser",
			"defaultValue":"",
			"noShow":true,
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"修改用户",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518664914,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-modifier",
			"tag":"JnpfInput",
			"tableAlign":"left",
			"span":24
		},
		"readonly":true,
		"prop":"F_LastModifyUserId",
		"width":null,
		"__vModel__":"F_LastModifyUserId",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"id":"F_LastModifyUserId",
		"placeholder":"系统自动生成",
		"labelI18nCode":""
	},
	{
		"jnpfKey":"modifyTime",
		"fullName":"修改时间",
		"fullNameI18nCode":[
			""
		],
		"label":"修改时间",
		"sortable":false,
		"align":"left",
		"__config__":{
			"formId":110,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"modifyTime",
			"defaultValue":"",
			"noShow":true,
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"修改时间",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518669233,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-modifytime",
			"tag":"JnpfInput",
			"tableAlign":"left",
			"span":24
		},
		"readonly":true,
		"prop":"F_LastModifyTime",
		"width":null,
		"__vModel__":"F_LastModifyTime",
		"fixed":"none",
		"style":{
			"width":"100%"
		},
		"id":"F_LastModifyTime",
		"placeholder":"系统自动生成",
		"labelI18nCode":""
	}
]
export default columnList