const searchList = [
	{
		"searchType":2,
		"jnpfKey":"billRule",
		"fullName":"采购单号",
		"fullNameI18nCode":[
			""
		],
		"label":"采购单号",
		"__config__":{
			"formId":101,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"billRule",
			"defaultValue":null,
			"noShow":false,
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"rule":"cgdj",
			"className":[],
			"label":"采购单号",
			"trigger":"change",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518489368,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-documents",
			"ruleName":"采购单据",
			"tag":"JnpfInput",
			"tableAlign":"left",
			"span":12
		},
		"readonly":true,
		"prop":"F_Purchase_number",
		"__vModel__":"F_Purchase_number",
		"searchMultiple":false,
		"isKeyword":false,
		"style":{
			"width":"100%"
		},
		"id":"F_Purchase_number",
		"placeholder":"系统自动生成",
		"labelI18nCode":""
	},
	{
		"clearable":true,
		"searchType":1,
		"jnpfKey":"usersSelect",
		"ableIds":[],
		"multiple":false,
		"fullName":"采购申请人",
		"fullNameI18nCode":[
			""
		],
		"label":"采购申请人",
		"__config__":{
			"formId":102,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"usersSelect",
			"defaultValue":"",
			"noShow":false,
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"采购申请人",
			"trigger":"change",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518535374,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-generator-founder",
			"defaultCurrent":false,
			"tag":"JnpfUsersSelect",
			"regList":[],
			"tableAlign":"left",
			"span":12
		},
		"prop":"F_Applys",
		"__vModel__":"F_Applys",
		"searchMultiple":true,
		"isKeyword":false,
		"style":{
			"width":"100%"
		},
		"selectType":"all",
		"disabled":false,
		"id":"F_Applys",
		"placeholder":"请选择",
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	},
	{
		"filterable":false,
		"clearable":true,
		"searchType":1,
		"jnpfKey":"depSelect",
		"ableIds":[],
		"multiple":false,
		"fullName":"所属部门",
		"fullNameI18nCode":[
			""
		],
		"label":"所属部门",
		"__config__":{
			"formId":103,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"depSelect",
			"defaultValue":"",
			"noShow":false,
			"tipLabel":"",
			"tableFixed":"none",
			"dragDisabled":false,
			"className":[],
			"label":"所属部门",
			"trigger":"change",
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518595157,
			"layout":"colFormItem",
			"tagIcon":"icon-ym icon-ym-tree-department1",
			"defaultCurrent":true,
			"tag":"JnpfDepSelect",
			"regList":[],
			"tableAlign":"left",
			"span":12
		},
		"prop":"F_Dep_Name",
		"__vModel__":"F_Dep_Name",
		"searchMultiple":true,
		"isKeyword":false,
		"style":{
			"width":"100%"
		},
		"selectType":"all",
		"disabled":false,
		"id":"F_Dep_Name",
		"placeholder":"请选择",
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	},
	{
		"clearable":true,
		"searchType":3,
		"jnpfKey":"datePicker",
		"format":"yyyy-MM-dd",
		"fullName":"采购申请日期",
		"fullNameI18nCode":[
			""
		],
		"label":"采购申请日期",
		"__config__":{
			"endRelationField":"",
			"defaultValue":null,
			"dragDisabled":false,
			"className":[],
			"showLabel":true,
			"required":false,
			"tableName":"test_purchase",
			"renderKey":1725518622997,
			"tagIcon":"icon-ym icon-ym-generator-date",
			"startRelationField":"",
			"defaultCurrent":false,
			"tag":"JnpfDatePicker",
			"formId":104,
			"visibility":[
				"pc",
				"app"
			],
			"jnpfKey":"datePicker",
			"noShow":false,
			"endTimeTarget":1,
			"tipLabel":"",
			"tableFixed":"none",
			"startTimeType":1,
			"endTimeRule":false,
			"label":"采购申请日期",
			"trigger":"change",
			"startTimeRule":false,
			"startTimeValue":null,
			"endTimeValue":null,
			"endTimeType":1,
			"layout":"colFormItem",
			"startTimeTarget":1,
			"regList":[],
			"tableAlign":"left",
			"span":12
		},
		"prop":"F_Purchase",
		"__vModel__":"F_Purchase",
		"searchMultiple":false,
		"isKeyword":false,
		"style":{
			"width":"100%"
		},
		"startTime":null,
		"disabled":false,
		"id":"F_Purchase",
		"placeholder":"请选择",
		"endTime":null,
		"value":[],
		"labelI18nCode":"",
		"on":{
			"change":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
			"blur":"({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
		}
	}
]
export default searchList